In [1]:
import tensorflow as tf
print (tf.__version__)

2.9.1


In [2]:
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
#check number of dimensions
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([3,3])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

In [5]:
#create a matrix 
matrix1 = tf.constant([[3,3],
                      [3,3]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]])>

In [6]:
#create matrix with dtype
matrix2= tf.constant([[3.3,3.3],
                      [3.3,3.3]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3.3, 3.3],
       [3.3, 3.3]], dtype=float16)>

In [7]:
#create 3x3 matrix
matrix3=tf.constant([[[3,3,3],
                      [3,3,3],
                      [3,3,3]]])
matrix3

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])>

In [8]:
#creating a tensor variable
var=tf.Variable([3,3])
const=tf.constant([3,3])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>

In [9]:
rand1 = tf.random.Generator.from_seed(42)
rand1=rand1.uniform(shape=(3,2))
rand2= tf.random.Generator.from_seed(42)
rand2=rand2.uniform(shape=(3,2))
rand1,rand2,rand1==rand2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [10]:
not_shuffled = tf.constant([[3,3],
                            [3,4],
                            [3,5]])
                            
                            
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 4],
       [3, 5]])>

In [11]:
tf.random.set_seed(30)
tf.random.shuffle(not_shuffled, seed=20)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 4],
       [3, 5]])>

In [12]:
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros([3,3], tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [14]:
import numpy as np
n1=np.arange(1,28,dtype=np.int32)
A=tf.constant(n1,shape=(3,3,3))
A

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [15]:
#creatibg a rank 4 tensor
rank_4_t=tf.zeros(shape=[3,3,3,3])
rank_4_t

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [16]:
tf.size(rank_4_t).numpy()

81

In [17]:
#getting first two elements of tensor
rank_4_t[:2,:1]

<tf.Tensor: shape=(2, 1, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [18]:
#get first element from each dimension 
rank_4_t[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0., 0., 0.]]]], dtype=float32)>

In [19]:
rank_2_t=tf.constant([[3,1],
                      [3,2]])
rank_2_t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 1],
       [3, 2]])>

In [20]:
rank_2_t.shape, rank_2_t.ndim

(TensorShape([2, 2]), 2)

In [21]:
rank_3_t=rank_2_t[...,tf.newaxis]
rank_3_t

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [1]],

       [[3],
        [2]]])>

In [22]:
tf.expand_dims(rank_2_t,axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [1]],

       [[3],
        [2]]])>

In [23]:
#manipulating tensors
t2=tf.constant([[3,3],[3,3]])
t2+10,t2-10,t2*10,t2/3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[13, 13],
        [13, 13]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-7, -7],
        [-7, -7]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[30, 30],
        [30, 30]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1., 1.],
        [1., 1.]])>)

In [24]:
t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]])>

In [25]:
#matrix multiplication
t1=tf.constant([[3,3],[3,3]])
tf.linalg.matmul(t1,t2), t1@t2
 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[18, 18],
        [18, 18]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[18, 18],
        [18, 18]])>)

In [26]:
t3=tf.random.Generator.from_seed(100)
t3=t3.uniform(shape=(3,2))
t4=tf.random.Generator.from_seed(200)
t4=t4.normal(shape=(3,2))
t3,t4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.6661966 , 0.7469058 ],
        [0.8769325 , 0.8477416 ],
        [0.22709787, 0.49256873]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.83051693,  1.543791  ],
        [-0.5432179 ,  0.36891136],
        [ 1.6245334 , -0.9666689 ]], dtype=float32)>)

In [27]:
t4=tf.reshape(t4,shape=(2,3))
t4

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.83051693,  1.543791  , -0.5432179 ],
       [ 0.36891136,  1.6245334 , -0.9666689 ]], dtype=float32)>

In [28]:
t3@t4

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.27774554,  2.2418418 , -1.0839005 ],
       [-0.4155658 ,  2.7309852 , -1.2958509 ],
       [-0.00689444,  1.150786  , -0.5995145 ]], dtype=float32)>

In [29]:
t5=tf.random.Generator.from_seed(300)
t5=t5.uniform(shape=(3,2))
t5

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.00473952, 0.06306279],
       [0.91214204, 0.46108627],
       [0.17251897, 0.9006287 ]], dtype=float32)>

In [30]:
t5=tf.transpose(t5)
t5

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.00473952, 0.91214204, 0.17251897],
       [0.06306279, 0.46108627, 0.9006287 ]], dtype=float32)>

In [31]:
t3@t5

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.05025942, 0.9520539 , 0.7876163 ],
       [0.05761719, 1.190769  , 0.9147879 ],
       [0.03213909, 0.4342622 , 0.48280022]], dtype=float32)>

In [32]:
tf.matmul(t3, tf.transpose(t4))

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [ ]:
t6 = tf.constant([3.3,3.3])
t6

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.3, 3.3], dtype=float32)>

In [ ]:
t6=tf.cast(t6, dtype= tf.float16)
t6

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.3, 3.3], dtype=float16)>

In [ ]:
t7 = tf.constant([3,3])
t7

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

In [ ]:
t7 = tf.cast(t7, dtype=tf.float16)
t7

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 3.], dtype=float16)>

In [ ]:
#getting the absolute values
t8 = tf.constant([-3,-3])
t8, tf.abs(t8)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -3])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>)

In [ ]:
#minimum of tensor
t9 = tf.constant(np.random.randint(0,100, size = 50))
t9, tf.reduce_min(t9)


(<tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([14, 16, 88, 75, 66, 77,  1, 33, 49, 19, 21, 60, 87, 72, 77, 67, 76,
        95, 90, 65,  9,  8,  9, 23, 97, 37, 97, 51, 53, 73, 58,  1, 12, 70,
        76, 97, 77, 64, 43, 27, 46, 14, 91, 74, 96, 50, 10, 93, 59, 18])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
#maximum of tensor
t10 = tf.constant(np.random.randint(0,300,size=100))
t10, tf.reduce_max(t10)

(<tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([ 35, 219,  87,  57, 113, 286, 263,  49, 210, 169, 161, 232,  71,
         76,  91, 244,   8,  57, 294, 251, 209, 292,  80,  25,  83, 281,
         92, 267, 164,  25, 176,  86, 133,  26, 105, 246,  54, 186, 168,
         56, 285, 272, 196, 123,  77, 118, 195,   5, 279, 266,  82,  23,
        212, 205,  34, 226, 152,  54,  99, 202,  48, 109, 204, 275,  88,
        243, 134, 136,  34, 170,  33,  43,  21,  97,  81, 267, 219, 269,
        265,  29, 285, 203, 104, 186, 233,  15,  51,   6, 264, 186, 200,
        187, 212, 236, 261, 153, 223,  30, 275, 113])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=294>)

In [ ]:
#sum of tensor
tf.reduce_sum(t10)

<tf.Tensor: shape=(), dtype=int32, numpy=15020>

In [ ]:
#variance of tensor
tf.math.reduce_variance(tf.cast(t10, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=8007.06>

In [ ]:
#standard deviation of tensor
tf.math.reduce_std(tf.cast(t10, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=89.48218>

In [ ]:
#positional maximum
tf.random.set_seed(33)
t11= tf.random.uniform(shape=[30])
t11, tf.reduce_max(t11), tf.argmax(t11)

(<tf.Tensor: shape=(30,), dtype=float32, numpy=
 array([0.33143902, 0.21867776, 0.0160141 , 0.2876439 , 0.79751086,
        0.21710753, 0.6433041 , 0.36862898, 0.50054467, 0.71634173,
        0.42660952, 0.53803957, 0.22099257, 0.81026185, 0.57730436,
        0.85869336, 0.3830887 , 0.10151541, 0.40971458, 0.53684866,
        0.675125  , 0.8787942 , 0.2530595 , 0.5888306 , 0.8912947 ,
        0.8457856 , 0.3994583 , 0.24162519, 0.581491  , 0.74078023],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.8912947>,
 <tf.Tensor: shape=(), dtype=int64, numpy=24>)

In [ ]:
t12=tf.random.normal(shape=[20])
t12, tf.reduce_min(t12), tf.argmin(t12)

(<tf.Tensor: shape=(20,), dtype=float32, numpy=
 array([-0.6311421 ,  0.13089854,  1.5443249 , -0.9973555 , -0.4522463 ,
         0.4891347 ,  0.29329988, -0.876649  ,  1.6094923 , -0.37898073,
         0.11001632, -1.9552854 ,  1.1763349 ,  0.024898  ,  0.05793991,
         1.0011885 , -0.25256434,  0.44457674,  0.56527317,  1.1908352 ],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-1.9552854>,
 <tf.Tensor: shape=(), dtype=int64, numpy=11>)

In [67]:
t13 = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
t13, tf.squeeze(t13)

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.11282897, 0.6076474 , 0.22263086, 0.34785545, 0.44322586,
            0.14974618, 0.15332222, 0.06837976, 0.42526126, 0.31326127,
            0.9021281 , 0.868147  , 0.8280438 , 0.5863085 , 0.8233335 ,
            0.26141036, 0.65921247, 0.9036591 , 0.0727607 , 0.49216378,
            0.9862461 , 0.50934017, 0.62700677, 0.9761859 , 0.61517644,
            0.6157739 , 0.24330997, 0.4313482 , 0.9485599 , 0.05677974,
            0.2609104 , 0.32276535, 0.5326617 , 0.29703486, 0.03984427,
            0.87294257, 0.6667284 , 0.2321918 , 0.34995997, 0.33859074,
            0.24336147, 0.06988668, 0.2758572 , 0.69293535, 0.6384758 ,
            0.9650717 , 0.5114281 , 0.6643033 , 0.5481446 , 0.5101727 ]]]]],
       dtype=float32)>,
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.11282897, 0.6076474 , 0.22263086, 0.34785545, 0.44322586,
        0.14974618, 0.15332222, 0.06837976, 0.42526126, 0.31326127,
        

In [33]:
#one hot encoding
list = [1,2,3,4]
tf.one_hot(list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [34]:
tf.one_hot(list, depth=4, on_value="T", off_value="F")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'F', b'T', b'F', b'F'],
       [b'F', b'F', b'T', b'F'],
       [b'F', b'F', b'F', b'T'],
       [b'F', b'F', b'F', b'F']], dtype=object)>

In [35]:
#squaring
t14=tf.range(0,10)
t14, tf.square(t14)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>)

In [36]:
#square rooting
tf.math.sqrt(tf.cast(t14, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [38]:
#log
tf.math.log(tf.cast(t14, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [39]:
#antilog
tf.math.antilog(tf.cast(t14, dtype=tf.float32))

AttributeError: module 'tensorflow._api.v2.math' has no attribute 'antilog'

In [43]:
#numpy and tensorflow
tf15=tf.constant(np.array([1,2,3]))
np.array(tf15), type(np.array(tf15))

(array([1, 2, 3]), numpy.ndarray)

In [46]:
t16=tf.constant(np.array([3.3,6,9]))
t17=tf.constant([3,6,9])
t16.dtype, t17.dtype

(tf.float64, tf.int32)

In [47]:
#checking device
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [54]:
#exercises
t18 = tf.constant(3)
t18.ndim, t18.shape, t18.dtype, tf.size(t18)

(0, TensorShape([]), tf.int32, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [56]:
t19 = tf.constant([3,3])
t19.ndim, t19.dtype, t19.shape, tf.size(t19)

(1, tf.int32, TensorShape([2]), <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [59]:
t20 = tf.constant([[3,3],[3,3]])
t20.ndim, t20.dtype, t20.shape, tf.size(t20)

(2, tf.int32, TensorShape([2, 2]), <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [63]:
t21 = tf.constant([[[3,3],[3,3]],[[3,3],[3,3]]])
t21.ndim, t21.dtype, t21.shape, tf.size(t21)

(3,
 tf.int32,
 TensorShape([2, 2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [82]:
t22 = tf.random.Generator.from_seed(10)
t22=t22.uniform(shape=[5,300])

In [81]:
t23 = tf.random.Generator.from_seed(20)
t23=t23.uniform(shape=[5,300])

In [83]:
tf.matmul(t22, t23, transpose_a=True)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.324576  , 0.60533017, 0.7899078 , ..., 0.6130224 , 0.833275  ,
        0.32714966],
       [0.5539023 , 0.77809733, 1.0149032 , ..., 0.5380521 , 1.0826046 ,
        0.7225168 ],
       [0.735603  , 0.61407447, 0.8310063 , ..., 0.7498543 , 1.2336272 ,
        0.8277302 ],
       ...,
       [1.1576127 , 1.4830979 , 1.4080607 , ..., 1.1800604 , 1.5160335 ,
        1.07214   ],
       [0.67203915, 0.98831743, 0.8486444 , ..., 0.5170104 , 0.586753  ,
        0.62804055],
       [0.59919417, 0.6023962 , 0.6523763 , ..., 0.39539665, 0.83830345,
        0.7118022 ]], dtype=float32)>

In [86]:
tf.tensordot(t22,tf.transpose(t23), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.348465, 75.50053 , 69.22717 , 75.14432 , 72.26243 ],
       [76.093285, 79.51416 , 74.59768 , 77.46012 , 75.1679  ],
       [71.64567 , 75.76221 , 72.32199 , 74.94431 , 73.525116],
       [70.39602 , 73.881   , 72.15695 , 72.372116, 71.00586 ],
       [72.72349 , 77.49847 , 72.379745, 74.86508 , 73.67624 ]],
      dtype=float32)>

In [97]:
t24=tf.range(1,11)
tf.argmax(t24)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [98]:
tf.one_hot(t24, depth =10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>